---
name: ArraySortTest
author: Matse
version: 1
description: Array sorting test using Python.

services:
  Small_load_Container:
    image: quoinedev/python3.7-pandas-alpine
    ports:
      - 9000:80
    setup-commands:
      - whoami
      - python3 -m pip install pandas
  High_load_Container:
    image: quoinedev/python3.7-pandas-alpine
    ports:
      - 9001:80
    setup-commands:
      - python3 -m pip install pandas

flow:
  - name: Sort 10 Million Elements
    container: Small_load_Container
    commands:
      - type: console
        command: python3 /tmp/repo/sort_test.py run -n 10000000
        detach: true
        note: Sorting array of 10 million elements detached
  - name: Sort 100 Million Elements
    container: High_load_Container
    commands:
      - type: console
        command: python3 /tmp/repo/sort_test.py run -n 100000000
        note: Sorting array of 100 million elements synchronously
  - name: Cleanup small load
    container: Small_load_Container
    commands:
      - type: console
        command: python3 /tmp/repo/sort_test.py cleanup
        note: Performing cleanup on Small_load_Container
  - name: Cleanup high load
    container: High_load_Container
    commands:
      - type: console
        command: python3 /tmp/repo/sort_test.py cleanup
        note: Performing cleanup on High_load_Container
